### ISSUE TITLE
ModuleNotFoundError pylexirumah 0.3

### ISSUE THREAD

**Issue by peterdekker** [Anaphory/lexirumah-data#121]
When using pylexirumah, version 0.3 from pypi, I get an error when loading the util module:

```
>>> import pylexirumah.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pylexirumah/util.py", line 16, in <module>
    from segment import tokenize_clpa, CLPA
ModuleNotFoundError: No module named 'segment'
```
I looked at the current source code on git, but this code seems to have changed in the meantime.

**Comment by Anaphory** [comment]
The segment module is a standalone separate module by someone else:
https://pypi.org/project/segments/ I seem to have forgotten it in the
dependencies. I'll try to fix the pylexirumah release soon.

Beyond that: If you want to use some functionality that is not specific to
LexiRumah, I may know about the state-of-the-art nowadays and be able to
help you, given that the last release of pylexirumah was a while ago and
the field is quite active.

**Comment by peterdekker** [comment]
Thanks! I installed the segments package, and had to install the last github version of pylexirumah (with the PyPI version pylexirumah=0.3, the problem persists):
```
pip3 install git+https://github.com/lessersunda/lexirumah-data.git
```

However, now a new problem happens when trying to load the dataset:
```
>>> lr = pylexirumah.util.get_dataset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pylexirumah/__init__.py", line 36, in get_dataset
    '{:} does not exist'.format(fname))
FileNotFoundError: /usr/local/lib/python3.6/dist-packages/cldf/cldf-metadata.json does not exist
```

My use case is the following, quite basic: I want to select a number of lects, and run an analysis on their word forms. I already managed to do this by reading ``lects.csv`` and ``forms.csv`` using pandas.read_csv(). I thought pylexirumah would maybe be easier/more elegant, but I can always revert to that solution.

**Comment by LinguList** [comment]
Why don't you use CLDF proper? As lexirumah is available in cldf, you 
can just load from there, using pycldf. Here's a tutorial on how to do 
this with WALS data: https://calc.hypotheses.org/2670 but lexical data 
is similar.

**Comment by Anaphory** [comment]
Indeed, for basic processing like that either pycldf (or, if it's just one data set, your favourite CSV reader and checking out the metadata file to understand the structure of the data) would be my way to go. I'm still going to have a look and fix the issues you encountered, it's been a while since I maintained pylexirumah properly.

**Comment by peterdekker** [comment]
Thanks both! I am looking into pycldf, as it seems a bit more principled way than opening the csv directly. However, I cannot find an efficient way to get the FormTable as a Pandas DataFrame out of pycldf? First getting a list of out, and importing that as a DataFrame seems inefficient to me, any ideas? I know not everybody uses Pandas, but for me it is an effective system to sort/group data or apply operations to whole columns :)

**Comment by LinguList** [comment]
I avoid pandas, so I can't help here, but if it is difficult to built a 
dataframe on the fly, this would surprise me a lot.

**Comment by peterdekker** [comment]
No, it is very simple, just ``pd.DataFrame(dataset['FormTable'])``. Was just thinking about computational efficiency, but actually the conversion goes fast (and it matters less, because it has to be done only once).

**Comment by LinguList** [comment]
If you use pandas, numpy, scipy you won't have computational efficiency 
anyway ;)
